[package]
name = "seed-calendar"
version = "0.1.0"
authors = ["glennsl <glenn@slotte.net>"]
edition = "2018"

[workspace]
members = [
    "examples/basic",
]

[dependencies]
chrono = "0.4.19"
js-sys = "0.3.50"
seed = "0.8.0"
wasm-bindgen = "0.2.73"
